### ISSUE TITLE
xlab not being rendered

### ISSUE THREAD

**Issue by timelyportfolio** [mcaule/d3_exploding_boxplot#1]
I love this and I'm working on wrapping it as an `htmlwidget` for `R` called [explodingboxplotR](https://github.com/timelyportfolio/explodingboxplotR).  As I was testing, I noticed that `xlab` does not get drawn in [line](https://github.com/mcaule/d3_exploding_boxplot/blob/master/src/d3_exploding_boxplot.js#L142).  I assume this is an oversight, but didn't know if it was intentional.  Happy to submit a pull if you would like.

Thanks again for this!

**Comment by mcaule** [comment]
Hi!
xlab was missing indeed. It's fixed now.
Thanks for the `htmlwidget` it's cool.

**Comment by timelyportfolio** [comment]
works great!  thanks.
