### ISSUE TITLE
No way to contact you?

### ISSUE THREAD

**Issue by TennisVisuals** [mcaule/d3_exploding_boxplot#3]
Sorry, I'm having difficulty finding a way to be in touch... other than opening an issue!

**Comment by micahstubbs** [comment]
@TennisVisuals the email for @mcaule from the `package. json` might be one way `matthieu.caule@gmail.com`

**Comment by micahstubbs** [comment]
hah! it looks like the answer is no 😂 

thanks for your contributions in the past @mcaule, don't worry about us now 😄
