### ISSUE TITLE
exploding_boxplot is not defined

### ISSUE THREAD

**Issue by om-nishu-trantor** [mcaule/d3_exploding_boxplot#4]
When I include all the required js files, i.e. `d3.js`, `d3.tip.js` and `d3_exploding_boxplot.js`
and write the code given here : http://mcaule.github.io/d3_exploding_boxplot/, then there is an issue that I encounter, i.e. :-
```javascript
VM94:1 Uncaught ReferenceError: exploding_boxplot is not defined
    at <anonymous>:1:1
```
If I write `var exploding_boxplot;` before inclusion of the javascript file, then it works.
Or if I modify the `d3_exploding_boxplot.js` to add the same variable definition `var exploding_boxplot;` then also it works fine.
Is there anything that I am missing ?

**Comment by om-nishu-trantor** [comment]
@mcaule , any thoughts ?

**Comment by mcaule** [comment]
Hello,

The exemple works with [requireJS](http://requirejs.org/). But if you dont want to use a module system, you have to reference exploding_boxplot as `d3.exploding_boxplot`

Be sure to load all the js files before executing your script.

Here is a working jsfiddle without requireJS : https://jsfiddle.net/fcyLr5kx/
